# Generated by Django 3.2.25 on 2025-03-06 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_location', models.CharField(max_length=255)),
                ('driving_hours', models.IntegerField()),
                ('rest_hours', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='trip',
            name='created_at',
        ),
        migrations.DeleteModel(
            name='LogSheet',
        ),
        migrations.AddField(
            model_name='logentry',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.trip'),
        ),
    ]
